version: "3.5"
services:
  db:
    image: postgres:latest
    environment:
       POSTGRES_USER: postgres
       POSTGRES_PASSWORD: password
       POSTGRES_DB: user_db_dio
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports: 
      - 5432:5432